spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moblog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    mode: HTMl
logging:
  level:
    root: info
    com.lrm: debug
  file:
    name: log/blog.log
comment.profile: /images/avatar.png
message.profile: /images/avatar.png
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mo.moblog.pojo